// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApEQZSzSf1Fua_FzGK41rmVjq0Ku28Fn0',
    appId: '1:82368886451:web:7f590bb0d6caa1b03da2c6',
    messagingSenderId: '82368886451',
    projectId: 'flutterchat-d8d60',
    authDomain: 'flutterchat-d8d60.firebaseapp.com',
    storageBucket: 'flutterchat-d8d60.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrnSvzqDvq0yNqwLlG7arJ9R2EyiNPSuo',
    appId: '1:82368886451:android:23b75c73e65aabee3da2c6',
    messagingSenderId: '82368886451',
    projectId: 'flutterchat-d8d60',
    storageBucket: 'flutterchat-d8d60.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRmS4-RUbQnTjjmAVys-ubjqeZEJvHz0M',
    appId: '1:82368886451:ios:2420c92028f064ca3da2c6',
    messagingSenderId: '82368886451',
    projectId: 'flutterchat-d8d60',
    storageBucket: 'flutterchat-d8d60.firebasestorage.app',
    iosBundleId: 'com.example.flutterChatNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRmS4-RUbQnTjjmAVys-ubjqeZEJvHz0M',
    appId: '1:82368886451:ios:2420c92028f064ca3da2c6',
    messagingSenderId: '82368886451',
    projectId: 'flutterchat-d8d60',
    storageBucket: 'flutterchat-d8d60.firebasestorage.app',
    iosBundleId: 'com.example.flutterChatNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApEQZSzSf1Fua_FzGK41rmVjq0Ku28Fn0',
    appId: '1:82368886451:web:7f7c11912f1fb3dd3da2c6',
    messagingSenderId: '82368886451',
    projectId: 'flutterchat-d8d60',
    authDomain: 'flutterchat-d8d60.firebaseapp.com',
    storageBucket: 'flutterchat-d8d60.firebasestorage.app',
  );
}
